<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DJBlaster\BlasterBundle\Entity\Customer;

/**
 * CustomerCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerCampaignRepository extends EntityRepository {
    public function findAllOrderedByNameForCustomer(Customer $customer) {
        return $this->findBy(array('customer' => $customer), array('campaign_name' => 'ASC'));
    }

}
