<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

use DJBlaster\BlasterBundle\Entity\AdPSA;
/**
 * DJReadPSARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DJReadPSARepository extends EntityRepository
{
    public function findAllForPSA(AdPSA $psa) {
        return $this->findBy(array('psa' => $psa), array('time_read' => 'ASC'));
    }
}
