<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

use DJBlaster\BlasterBundle\Entity\AdEvent;
/**
 * DJReadEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DJReadEventRepository extends EntityRepository
{
    public function findAllForEvent(AdEvent $event) {
        return $this->findBy(array('event' => $event), array('time_read' => 'ASC'));
    }
}
