<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

use DJBlaster\BlasterBundle\Entity\AdShowSponsorship;
/**
 * DJReadShowSponsorshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DJReadShowSponsorshipRepository extends EntityRepository
{
    public function findAllForShow(AdShowSponsorship $show) {
        return $this->findBy(array('showSponsorship' => $show), array('time_read' => 'ASC'));
    }
}
