<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

use DJBlaster\BlasterBundle\Entity\AdEvent;

/**
 * DJReadEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DJReadEventRepository extends EntityRepository
{
    public function findAllForEvent(AdEvent $event)
    {
        return $this->findBy(array('event' => $event), array('time_read' => 'ASC'));
    }

    public function getRecentReads($numToGet)
    {
        $fields = array(
            'r.dj_initials',
            'r.time_read',
            'e.ad_name',
            'u.id as customer_id',
            'u.name as customer_name',
            'c.campaign_id',
            'c.campaign_name'
        );

        $qb = $this->createQueryBuilder('r');
        $query = $qb->select($fields)
            ->innerJoin('DJBlasterBundle:AdEvent', 'e', 'WITH', 'e.event_id = r.event')
            ->innerJoin('DJBlasterBundle:CustomerCampaign', 'c', 'WITH', 'c.campaign_id = e.campaign')
            ->innerJoin('DJBlasterBundle:Customer', 'u', 'WITH', 'u.id = e.customer')
            ->orderBy('r.time_read', 'DESC')
            ->setMaxResults($numToGet)
            ->getQuery();

        $result =  $query->getResult();
        //echo $query->getSql();var_dump($query->getParameters());die;
        return $result;
    }
}