<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DJSignInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DJSignInRepository extends EntityRepository
{
    public function getDJSigninsBetweenDates($start_date, $end_date){
        $q = $this
           ->createQueryBuilder('e')
           ->where('e.signin_datetime >= :start_date')
           ->andWhere('e.signin_datetime <= :end_date')
           ->setParameter('start_date', $start_date)
           ->setParameter('end_date', $end_date)
           ->getQuery();

        return $q->getArrayResult();

    }
}
