<?php

namespace DJBlaster\BlasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
    public function findAllOrderedByName() {
        return $this->findBy(array(), array('name' => 'ASC'));
    }

    public function findOneByEmail($email) {
        return $this->findOneBy(array('email' => $email));
    }

}
